"""Generated executive maps: root map sections rebuilt from `memory-store/` subtrees.

Store-first model (ROADMAP Phase 2): the semantic `memory-store/` tree is the only
hand-written source of truth for facts. Root map files (`architecture.md`,
`decisions.md`, ...) are compact generated views over one top-level store category
each. Generation is deterministic given the store state, so maps produce stable,
PR-reviewable diffs and cannot drift from the store.

Hand-written content is never silently destroyed: a legacy (pre-store-first) map
body, or a generated map body that was hand-edited after generation, is folded
into `memory-store/<category>/map-notes-pending-review.md` before the map is
rebuilt, so the next Dreaming pass can consolidate it into granular memories.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path
from typing import Any

from memory_fabric.contracts import MapsRegenResult
from memory_fabric.frontmatter import FrontmatterError, dump_frontmatter, parse_frontmatter
from memory_fabric.storage._shared import (
    CURRENT_SCHEMA_VERSION,
    PRIORITY_ORDER,
    STEERING_SECTIONS,
    _iter_markdown_files,
    _path_to_store_path,
    estimate_tokens,
)
from memory_fabric.templates import SECTION_TEMPLATES, now_iso

# Store file that receives hand-written map content before a map is rebuilt.
FOLD_BASENAME = "map-notes-pending-review"

# Soft token cap for a generated map body. Lowest-priority entries beyond the
# cap are elided in favor of a pointer to memory-store/index.md, keeping maps
# cheap in the combined-context budget. Override: MEMORY_FABRIC_MAP_TOKEN_CAP.
_MAP_TOKEN_CAP_DEFAULT = 600

_GENERATED_MARKER = (
    "Generated by Memory Fabric from `memory-store/{category}/` — do not edit by hand. "
    "Write facts with `write_memory_store_tool`; Dreaming rebuilds this map."
)


def _map_token_cap() -> int:
    try:
        cap = int(os.environ.get("MEMORY_FABRIC_MAP_TOKEN_CAP", ""))
        if cap > 0:
            return cap
    except (ValueError, TypeError):
        pass
    return _MAP_TOKEN_CAP_DEFAULT


def _category_entries(
    store_root: Path, category: str, warnings: list[str] | None = None
) -> list[dict[str, Any]]:
    """Collect the map inputs (path, title, summary, priority) for one category."""
    category_root = store_root / category
    if not category_root.exists():
        return []
    entries: list[dict[str, Any]] = []
    for path in _iter_markdown_files(category_root):
        if path.name == "index.md":
            continue
        try:
            metadata, _body = parse_frontmatter(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, FrontmatterError) as exc:
            # A fact that fails to parse must not silently vanish from the
            # generated map — that looks identical to "never recorded".
            if warnings is not None:
                warnings.append(f"Excluded {path.relative_to(store_root)} from its map: {exc}")
            continue
        entries.append(
            {
                "store_path": _path_to_store_path(store_root, path),
                "title": str(metadata.get("title") or path.stem.replace("-", " ").title()),
                "summary": str(metadata.get("summary") or ""),
                "priority": str(metadata.get("priority") or "medium"),
            }
        )
    entries.sort(key=lambda e: (PRIORITY_ORDER.get(e["priority"], 1), e["store_path"]))
    return entries


def _fingerprint_entries(entries: list[dict[str, Any]]) -> str:
    """Deterministic fingerprint over exactly the store fields a map is built from.

    Stored in the map's frontmatter as `store_fingerprint`; eval recomputes it
    from the live store to detect stale maps without relying on file mtimes
    (which git checkouts rewrite).
    """
    digest = hashlib.md5()
    for entry in entries:
        line = f"{entry['store_path']}|{entry['title']}|{entry['summary']}|{entry['priority']}\n"
        digest.update(line.encode("utf-8"))
    return digest.hexdigest()


def category_fingerprint(store_root: Path, category: str) -> str:
    """Fingerprint of a store category's current map inputs."""
    return _fingerprint_entries(_category_entries(store_root, category))


def _build_map_body(category: str, entries: list[dict[str, Any]]) -> str:
    title = category.replace("-", " ").replace("_", " ").title()
    lines = [
        f"# {title} Map",
        "",
        _GENERATED_MARKER.format(category=category),
        "",
    ]
    cap = _map_token_cap()
    for included, entry in enumerate(entries):
        summary = entry["summary"].replace("\n", " ").strip()
        line = f"- **{entry['title']}** (`{entry['store_path']}`, {entry['priority']}) — {summary}"
        if included > 0 and estimate_tokens("\n".join([*lines, line])) > cap:
            remaining = len(entries) - included
            lines.append(f"- …and {remaining} more entries — see `memory-store/index.md`.")
            break
        lines.append(line)
    return "\n".join(lines) + "\n"


def _body_hash(body: str) -> str:
    return hashlib.md5(body.strip().encode("utf-8")).hexdigest()


def _is_starter_placeholder(category: str, body: str) -> bool:
    """True when a map body is just the init starter template (nothing to fold)."""
    normalized = " ".join(body.split()).strip().lower()
    if not normalized:
        return True
    template_body = str(SECTION_TEMPLATES.get(category, {}).get("body", ""))
    if normalized == " ".join(template_body.split()).strip().lower():
        return True
    return "this is an executive map" in normalized and len(normalized) < 200


def _fold_into_store(store_root: Path, category: str, section_name: str, body: str) -> str | None:
    """Preserve hand-written map content as a store entry marked for review.

    Returns the store path written, or None when the content was already folded
    (exact body block present) and nothing changed.
    """
    target_dir = store_root / category
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / f"{FOLD_BASENAME}.md"
    store_path = f"{category}/{FOLD_BASENAME}"

    block = f"## Folded from `{section_name}.md` on {now_iso()}\n\n{body.strip()}\n"

    if target.exists():
        try:
            metadata, existing = parse_frontmatter(target.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, FrontmatterError):
            metadata, existing = {}, ""
        if body.strip() and body.strip() in existing:
            return None
        new_body = (existing.rstrip() + "\n\n" + block) if existing.strip() else block
    else:
        metadata = {
            "store_path": store_path,
            "title": f"{category.replace('-', ' ').title()} Map Notes (Pending Review)",
            "summary": (
                f"Hand-written notes folded from {section_name}.md; "
                "split into granular memories and delete."
            ),
            "priority": "medium",
            "tags": ["needs-review", "legacy-map"],
            "schema_version": CURRENT_SCHEMA_VERSION,
        }
        new_body = block

    metadata["last_updated"] = now_iso()
    target.write_text(dump_frontmatter(metadata, new_body), encoding="utf-8")
    return store_path


def _generate_category_map(
    memory_root: Path,
    store_root: Path,
    category: str,
    warnings: list[str],
    old_meta: dict[str, Any] | None = None,
) -> str | None:
    """(Re)build one root map from its store category subtree.

    Returns the filename written, or None when the category has no entries yet
    (the starter map is left alone) or the existing generated map is already up
    to date. Folding hand-written content is the caller's concern — this
    overwrites whatever is at ``<category>.md``, so callers must either fold
    first (`regenerate_maps`) or have already granularized the body into the
    store (`migrate_memory`).

    ``old_meta``: pass pre-parsed frontmatter of the existing map to avoid a
    second read; None means "read it here".
    """
    map_path = memory_root / f"{category}.md"
    if old_meta is None:
        old_meta = {}
        if map_path.exists():
            try:
                old_meta, _ = parse_frontmatter(map_path.read_text(encoding="utf-8"))
            except Exception as exc:  # noqa: BLE001 - reported via warnings, not swallowed.
                warnings.append(f"Could not parse existing map {map_path.name}: {exc}")

    entries = _category_entries(store_root, category, warnings=warnings)
    if not entries:
        # Nothing recorded for this category yet: leave the starter map alone.
        return None

    fingerprint = _fingerprint_entries(entries)
    body = _build_map_body(category, entries)

    # body_hash compares stripped content: frontmatter round-trips may move
    # a leading/trailing newline, which must not count as a change.
    unchanged = (
        bool(old_meta.get("generated"))
        and str(old_meta.get("store_fingerprint") or "") == fingerprint
        and str(old_meta.get("body_hash") or "") == _body_hash(body)
    )
    if unchanged:
        return None

    template = SECTION_TEMPLATES.get(category, {})
    metadata: dict[str, Any] = {
        "section": category,
        "summary": f"Generated map of memory-store/{category}/ ({len(entries)} entries).",
        "priority": str(old_meta.get("priority") or template.get("priority") or "medium"),
        "tags": old_meta.get("tags") or template.get("tags") or [category],
        "schema_version": CURRENT_SCHEMA_VERSION,
        "last_updated": now_iso(),
        "generated": True,
        "generated_from": f"memory-store/{category}",
        "store_fingerprint": fingerprint,
        "body_hash": _body_hash(body),
    }
    map_path.write_text(dump_frontmatter(metadata, body), encoding="utf-8")
    return map_path.name


def regenerate_maps(memory_root: Path) -> MapsRegenResult:
    """Regenerate root map sections from the memory-store tree under ``memory_root``.

    Works on either the live `.ai-memory/` directory or a Dreaming candidate root
    (same layout). One map is (re)built per non-empty top-level store category;
    steering sections are never touched. Maps whose store inputs are unchanged
    are skipped entirely, so repeated runs produce no diff noise.
    """
    warnings: list[str] = []
    maps_written: list[str] = []
    legacy_folded: list[str] = []

    # The store directory may not exist yet (candidate roots only copy .md
    # files); folding a hand-edited generated map creates it on demand.
    store_root = memory_root / "memory-store"
    categories: set[str] = (
        {p.name for p in store_root.iterdir() if p.is_dir()} if store_root.exists() else set()
    )
    # Root files already flagged `generated` participate even when their store
    # category is still empty: a hand edit on such a map must be folded into
    # the store (creating the category) rather than sit invisible to Dreaming.
    for path in memory_root.glob("*.md"):
        if path.name == "index.md":
            continue
        try:
            file_meta, _ = parse_frontmatter(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, FrontmatterError) as exc:
            warnings.append(f"Could not check {path.name} for a hand-edited generated map: {exc}")
            continue
        if file_meta.get("generated"):
            categories.add(path.stem)

    for category in sorted(categories):
        if category in STEERING_SECTIONS:
            # Steering sections are hand-curated, always-loaded directives; a
            # generated map would overwrite them. The category stays reachable
            # through memory-store/index.md and context assembly.
            continue

        map_path = memory_root / f"{category}.md"
        old_meta: dict[str, Any] = {}
        old_body = ""
        if map_path.exists():
            try:
                old_meta, old_body = parse_frontmatter(map_path.read_text(encoding="utf-8"))
            except Exception as exc:  # noqa: BLE001 - reported via warnings, not swallowed.
                warnings.append(f"Could not parse existing map {map_path.name}: {exc}")

        # Fold hand-written content into the store before overwriting: either a
        # legacy (pre-store-first) map, or a generated map whose body was edited
        # after generation (recorded body hash no longer matches).
        if old_body.strip():
            recorded_hash = str(old_meta.get("body_hash") or "")
            hand_written = (not old_meta.get("generated")) or (
                recorded_hash != _body_hash(old_body)
            )
            if hand_written and not _is_starter_placeholder(category, old_body):
                folded = _fold_into_store(store_root, category, map_path.stem, old_body)
                if folded:
                    legacy_folded.append(folded)
                    warnings.append(
                        f"Hand-written content from {map_path.name} was preserved at "
                        f"memory-store/{folded}.md for review before regenerating the map."
                    )

        written = _generate_category_map(
            memory_root, store_root, category, warnings, old_meta=old_meta
        )
        if written:
            maps_written.append(written)

    return {
        "maps_written": maps_written,
        "legacy_folded": legacy_folded,
        "warnings": warnings,
    }
