"""MCP server entrypoint for Memory Fabric."""

from __future__ import annotations

from memory_fabric.eval import evaluate_dream_quality, evaluate_memory_fabric
from memory_fabric.paths import validate_cwd
from memory_fabric.storage import (
    delete_memory_store,
    dream,
    initialize_memory_fabric,
    keyword_search,
    list_memory_store,
    propose_memory_patch,
    read_combined_context,
    read_memory_store,
    read_section,
    write_local_memory,
    write_memory_store,
    write_session_journal,
    prepare_dream_payload,
    apply_dream_results,
)

try:
    from mcp.server.fastmcp import FastMCP, Context
except ImportError:  # pragma: no cover - exercised only when optional mcp is absent.
    FastMCP = None  # type: ignore[assignment]
    Context = None


if FastMCP is not None:
    from memory_fabric.llm import load_env_from_cwd

    mcp = FastMCP("Memory Fabric")

    def _safe_cwd(cwd: str) -> str:
        """Validate the agent-supplied cwd and load .env before any tool call.

        Raises ValueError if cwd is empty, non-existent, or resolves to a
        dangerous system path (path traversal protection).
        """
        safe = validate_cwd(cwd)
        load_env_from_cwd(str(safe))
        return str(safe)

    @mcp.tool()
    def initialize_memory_fabric_tool(cwd: str, memory_prompt: str | None = None):
        safe = _safe_cwd(cwd)
        return initialize_memory_fabric(safe, memory_prompt=memory_prompt)

    @mcp.tool()
    def read_combined_context_tool(cwd: str, max_tokens: int | None = None, query: str | None = None):
        safe = _safe_cwd(cwd)
        return read_combined_context(safe, max_tokens=max_tokens, query=query)

    @mcp.tool()
    def read_section_tool(cwd: str, section: str, max_tokens: int = 8000):
        safe = _safe_cwd(cwd)
        return read_section(safe, section=section, max_tokens=max_tokens)

    @mcp.tool()
    def keyword_search_tool(cwd: str, query: str, max_results: int = 10):
        safe = _safe_cwd(cwd)
        return keyword_search(safe, query=query, max_results=max_results)

    @mcp.tool()
    def write_local_memory_tool(cwd: str, section: str, content: str, mode: str = "append"):
        safe = _safe_cwd(cwd)
        return write_local_memory(safe, section=section, content=content, mode=mode)  # type: ignore[arg-type]

    @mcp.tool()
    def propose_memory_patch_tool(cwd: str, instructions: str):
        safe = _safe_cwd(cwd)
        return propose_memory_patch(safe, instructions=instructions)

    @mcp.tool()
    async def dream_tool(
        cwd: str,
        mode: str = "light",
        apply: bool = False,
        llm_rewrite: bool = False,
        max_rewrite_tasks: int = 5,
        with_eval: bool = False,
        save_report: bool = False,
        llm_review: bool = False,
        context: Context = None,
    ):
        safe = _safe_cwd(cwd)
        result = await dream(
            safe,
            mode=mode,
            apply=apply,
            llm_rewrite=llm_rewrite,
            max_rewrite_tasks=max_rewrite_tasks,
            context=context,
        )
        if with_eval and apply and result["snapshot"]:
            # NOTE: save_report and llm_review are now correctly forwarded (bug fix).
            result["evaluation"] = await evaluate_dream_quality(
                safe,
                snapshot=result["snapshot"],
                save_report=save_report,
                llm_review=llm_review,
                context=context,
            )
        elif with_eval and not apply:
            result["warnings"].append("Dream evaluation requires apply=true because candidate mode does not mutate live memory.")
        return result


    @mcp.tool()
    def prepare_dream_payload_tool(cwd: str, mode: str = "light"):
        """Prepare prompt and payload for client-agent to perform consolidation."""
        safe = _safe_cwd(cwd)
        return prepare_dream_payload(safe, mode=mode)

    @mcp.tool()
    async def apply_dream_results_tool(
        cwd: str,
        candidate_store: str,
        llm_response: str,
        mode: str = "light",
        apply: bool = True,
        llm_rewrite: bool = False,
        max_rewrite_tasks: int = 5,
        context: Context = None,
    ):
        """Apply consolidation results generated by the client-agent's LLM run."""
        safe = _safe_cwd(cwd)
        return await apply_dream_results(
            safe,
            candidate_store=candidate_store,
            llm_response=llm_response,
            mode=mode,
            apply=apply,
            llm_rewrite=llm_rewrite,
            max_rewrite_tasks=max_rewrite_tasks,
            context=context,
        )

    @mcp.tool()
    async def evaluate_memory_fabric_tool(cwd: str, save_report: bool = False, llm_review: bool = False, context: Context = None):
        safe = _safe_cwd(cwd)
        return await evaluate_memory_fabric(safe, save_report=save_report, llm_review=llm_review, context=context)

    @mcp.tool()
    async def evaluate_dream_quality_tool(
        cwd: str,
        snapshot: str,
        save_report: bool = False,
        llm_review: bool = False,
        context: Context = None,
    ):
        safe = _safe_cwd(cwd)
        return await evaluate_dream_quality(safe, snapshot=snapshot, save_report=save_report, llm_review=llm_review, context=context)

    @mcp.tool()
    def write_memory_store_tool(
        cwd: str,
        store_path: str,
        content: str,
        title: str = "",
        tags: str = "",
        priority: str = "medium",
        mode: str = "replace",
    ):
        """Write a memory file to a semantic store path (e.g. 'architecture/decisions/auth-service')."""
        safe = _safe_cwd(cwd)
        tag_list = [t.strip() for t in tags.split(",") if t.strip()] if tags else None
        return write_memory_store(
            safe, store_path=store_path, content=content,
            title=title, tags=tag_list, priority=priority, mode=mode,  # type: ignore[arg-type]
        )

    @mcp.tool()
    def read_memory_store_tool(
        cwd: str,
        store_path: str,
        max_tokens: int = 8000,
    ):
        """Read a single memory-store file by its semantic path."""
        safe = _safe_cwd(cwd)
        return read_memory_store(safe, store_path=store_path, max_tokens=max_tokens)

    @mcp.tool()
    def list_memory_store_tool(
        cwd: str,
        prefix: str = "",
        tags: str = "",
        max_results: int = 50,
    ):
        """List files in the memory store, optionally filtered by prefix and/or tags."""
        safe = _safe_cwd(cwd)
        tag_list = [t.strip() for t in tags.split(",") if t.strip()] if tags else None
        return list_memory_store(safe, prefix=prefix, tags=tag_list, max_results=max_results)

    @mcp.tool()
    def delete_memory_store_tool(
        cwd: str,
        store_path: str,
    ):
        """Remove a memory-store file by its semantic path."""
        safe = _safe_cwd(cwd)
        return delete_memory_store(safe, store_path=store_path)

    @mcp.tool()
    def write_session_journal_tool(
        cwd: str,
        summary: str,
        key_decisions: list[str] | None = None,
        files_changed: list[str] | None = None,
        session_label: str | None = None,
    ):
        """Append a timestamped session journal to the episodic memory store.

        Creates or appends to an `episodic/YYYY-MM-DD` store entry that records
        what was accomplished this session. Multiple calls on the same day accumulate
        into a single dated journal file. Dreaming consolidates old entries (>7 days)
        into monthly summaries.

        Args:
            summary:        2-4 sentence description of what was done this session.
            key_decisions:  Optional list of architecture decisions or choices made.
            files_changed:  Optional list of files created or significantly modified.
            session_label:  Optional short label (e.g. 'auth-refactor'). Defaults to HH:MM UTC.
        """
        safe = _safe_cwd(cwd)
        return write_session_journal(
            safe,
            summary=summary,
            key_decisions=key_decisions,
            files_changed=files_changed,
            session_label=session_label,
        )

else:
    mcp = None


def main(argv: list[str] | None = None) -> int:
    if mcp is None:
        raise SystemExit("The optional `mcp` package is not installed. Install with: pipx inject memory-fabric mcp")
        
    import argparse
    parser = argparse.ArgumentParser(prog="memory-fabric-mcp", description="Memory Fabric MCP Server")
    parser.add_argument("--transport", choices=["stdio", "sse"], default="stdio", help="Transport protocol to use (default: stdio)")
    parser.add_argument("--host", default="127.0.0.1", help="Host address for SSE transport (default: 127.0.0.1)")
    parser.add_argument("--port", type=int, default=8000, help="Port for SSE transport (default: 8000)")
    parser.add_argument("--allow-all-origins", action="store_true", help="Allow all origins and disable DNS rebinding protection (useful for Open WebUI)")
    
    args = parser.parse_args(argv)
    
    if args.transport == "sse":
        mcp.settings.host = args.host
        mcp.settings.port = args.port
        if args.allow_all_origins:
            mcp.settings.transport_security.enable_dns_rebinding_protection = False
            mcp.settings.transport_security.allowed_hosts = ["*"]
            mcp.settings.transport_security.allowed_origins = ["*"]
        print(f"Starting Memory Fabric MCP server on sse://{args.host}:{args.port}")
        mcp.run(transport="sse")
    else:
        mcp.run(transport="stdio")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
